const IMAGES={
    C:require('../assets/c.jpg').default,
    CPP:require('../assets/cpp.jpg').default,
    HTML:require('../assets/html.jpg').default,
    CSS:require('../assets/css.jpg').default,
    SPRING:require('../assets/SPRINGBOOT.jpg').default,
    NODE:require('../assets/node.jpg').default,
    PHP:require('../assets/php.jpg').default,
    PYTHON:require('../assets/python.jpg').default,
    JS:require('../assets/js.jpg').default,
    JAVA:require('../assets/java.jpg').default,
    REACT:require('../assets/react.jpg').default,
    DBMS:require('../assets/DBMS.jpg').default,
    STATISTICS:require('../assets/STATISTICS.jpg').default,
    FA:require('../assets/FA.jpg').default,
    BM:require('../assets/BM.jpg').default,
    RDBMD:require('../assets/RDBMS.jpg').default,
    DS:require('../assets/DS.jpg').default,
    SE:require('../assets/SE.jpg').default,
    BIGDATA:require('../assets/BIG-DATA.jpg').default,
    NODEJS:require('../assets/M-IMG/NODE.jpg').default,
    ADVANCEPHP:require('../assets/ADVANCE-PHP.jpg').default,
    HADOOP:require('../assets/HADOOP.jpg').default,
    OOSE:require('../assets/images (2).jpg').default,
    MONGODB:require('../assets/MONGO.jpg').default,
    ANDROID:require('../assets/download.jpg').default,
    DOTNET:require('../assets/DOT-NET.jpg').default,
    ANGULAR:require('../assets/ANGULAR.jpg').default,
    OS:require('../assets/OS.jpg').default,
}
export default IMAGES;

